# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='import.proto',
  package='import_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cimport.proto\x12\x0cimport_proto\"*\n\x0fimportedMessage\x12\x17\n\x0fimported_string\x18\x04 \x01(\tb\x06proto3'
)




_IMPORTEDMESSAGE = _descriptor.Descriptor(
  name='importedMessage',
  full_name='import_proto.importedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imported_string', full_name='import_proto.importedMessage.imported_string', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['importedMessage'] = _IMPORTEDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

importedMessage = _reflection.GeneratedProtocolMessageType('importedMessage', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTEDMESSAGE,
  '__module__' : 'import_pb2'
  # @@protoc_insertion_point(class_scope:import_proto.importedMessage)
  })
_sym_db.RegisterMessage(importedMessage)


# @@protoc_insertion_point(module_scope)
