# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import test_pb2 as proto_dot_test__pb2


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test = channel.unary_unary(
                '/TestService/Test',
                request_serializer=proto_dot_test__pb2.TestRequest.SerializeToString,
                response_deserializer=proto_dot_test__pb2.TestResponse.FromString,
                )
        self.TestStream = channel.stream_stream(
                '/TestService/TestStream',
                request_serializer=proto_dot_test__pb2.TestRequest.SerializeToString,
                response_deserializer=proto_dot_test__pb2.TestResponse.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=proto_dot_test__pb2.TestRequest.FromString,
                    response_serializer=proto_dot_test__pb2.TestResponse.SerializeToString,
            ),
            'TestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestStream,
                    request_deserializer=proto_dot_test__pb2.TestRequest.FromString,
                    response_serializer=proto_dot_test__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestService/Test',
            proto_dot_test__pb2.TestRequest.SerializeToString,
            proto_dot_test__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/TestService/TestStream',
            proto_dot_test__pb2.TestRequest.SerializeToString,
            proto_dot_test__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TestService2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test = channel.unary_unary(
                '/TestService2/Test',
                request_serializer=proto_dot_test__pb2.TestRequest.SerializeToString,
                response_deserializer=proto_dot_test__pb2.TestResponse.FromString,
                )
        self.TestStream = channel.stream_stream(
                '/TestService2/TestStream',
                request_serializer=proto_dot_test__pb2.TestRequest.SerializeToString,
                response_deserializer=proto_dot_test__pb2.TestResponse.FromString,
                )


class TestService2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestService2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=proto_dot_test__pb2.TestRequest.FromString,
                    response_serializer=proto_dot_test__pb2.TestResponse.SerializeToString,
            ),
            'TestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestStream,
                    request_deserializer=proto_dot_test__pb2.TestRequest.FromString,
                    response_serializer=proto_dot_test__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestService2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestService2/Test',
            proto_dot_test__pb2.TestRequest.SerializeToString,
            proto_dot_test__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/TestService2/TestStream',
            proto_dot_test__pb2.TestRequest.SerializeToString,
            proto_dot_test__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
